main: com.tich.br.Main
name: BuildersRemorse
version: v1.01
api-version: 1.14
author: Evan Tichenor (evan.tichenor@gmail.com)
description: A plugin that prevents players from destroying blocks that were placed by players. Build wisely.
commands:
  buildersremorse:
    description: Shows which version of Builders Remorse is on the server.
    aliases: [br]
    usage: /br [remove | enable | disable | version | help]
    permission: buildersremorse.br
    permission-message: You don't have permission to use this command.